set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports pwm1[0]]
set_property PACKAGE_PIN B12 [get_ports pwm1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports pwm1[1]]
set_property PACKAGE_PIN C12 [get_ports pwm1[1]]

set_property PACKAGE_PIN A18 [get_ports jiaodu[0]]
set_property IOSTANDARD LVCMOS33 [get_ports jiaodu[0]]
set_property PACKAGE_PIN B18 [get_ports jiaodu[1]]
set_property IOSTANDARD LVCMOS33 [get_ports jiaodu[1]]
set_property PACKAGE_PIN B17 [get_ports jiaodu[2]]
set_property IOSTANDARD LVCMOS33 [get_ports jiaodu[2]]
set_property PACKAGE_PIN B16 [get_ports jiaodu[3]]
set_property IOSTANDARD LVCMOS33 [get_ports jiaodu[3]]
set_property PACKAGE_PIN D17 [get_ports jiaodu[4]]
set_property IOSTANDARD LVCMOS33 [get_ports jiaodu[4]]